---
ansible_connection: netconf
ansible_network_os: junos
ansible_user: root
ansible_password: Neratel123+
# Above connection variable for the switch

vlan:
  - name: vlan102
    vlanid: 102
  - name: vlan103
    vlanid: 103
